Fix/file stream unseekable
teamclairvoyant/airflow-rest-api-plugin pull request #66
Opened 2020-05-27 16:53 UTC by damilare

2020-05-28 07:11 UTC, pobtastic commented
LGTM 👍

2020-07-07 15:45 UTC, rssanders3 requested changes

2020-07-07 15:45 UTC, rssanders3 commented on plugins/rest_api_plugin.py
> +        if not dag_archive.filename.endswith('.zip'):
Allow uppercase as well?

2020-07-07 15:45 UTC, rssanders3 commented on plugins/rest_api_plugin.py
> +        force = True if request.form.get('force') is not None else False
There doesn't appear to be a force option in the arguments or post_arguments

2021-05-10 08:47 UTC, closed without merging